# Generated by Django 2.1.4 on 2019-01-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddr_music_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='name',
            field=models.CharField(default='test', max_length=255, verbose_name='楽曲名'),
            preserve_default=False,
        ),
    ]
