# Generated by Django 2.1.4 on 2019-01-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddr_music_view', '0002_music_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(default='Test', max_length=255, verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='version',
            field=models.CharField(default='Test', max_length=255, verbose_name='バージョン'),
            preserve_default=False,
        ),
    ]
