# Generated by Django 2.1.4 on 2019-01-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddr_music_view', '0003_auto_20190108_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='max_bpm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='min_bpm',
            field=models.IntegerField(default=0),
        ),
    ]
